Adding taxonomical subheading
unitaryfund/metriq-app pull request #680
Opened 2022-08-27 12:35 UTC by vprusso

Closes: #658 

Adding a one-sentence description for each menu item.

2022-08-29 19:36 UTC, WrathfulSpatula approved these changes
If you make this something like a `<ViewSubHeader>` component instead of `<h5>`, just like `<ViewHeader>`, then we can change all instances in one place in code, if heading layout changes and `<h5>` is no longer appropriate. Otherwise, we'd have to string search for every instance of `<h5>`, if things change.

2022-08-29 19:36 UTC, WrathfulSpatula requested changes
See my earlier comment. (I hit the wrong option.)

2022-08-29 19:39 UTC, WrathfulSpatula commented
Or, you could make it a string property of a `<ViewHeader>`. That way, it's inside of the containing `<header>` tag in that component.

2022-08-29 23:33 UTC, vprusso commented
@WrathfulSpatula great suggestion. Makes sense. Done!

2022-08-31 18:32 UTC, WrathfulSpatula commented on src/views/Methods.js
> +          <ViewHeader>Methods are the algorithms used in a submission.</ViewHeader>
I think you meant to put this in `<ViewSubHeader>`.

2022-08-31 18:32 UTC, WrathfulSpatula commented on src/views/Platforms.js
> +          <ViewHeader>Platforms are the hardware devices used for a submission.</ViewHeader>
Same here: I think you meant to put this in `<ViewSubHeader>`.

2022-09-01 23:53 UTC, merged